version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  # redis:
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"