services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  # redis:
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"


volumes:
  postgres_data:
